config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  get 'stat' => 'pages#stat'
  post 'stat' => 'pages#stat'
  get 'superscore' => 'pages#superscore'

end

app/models/superuser.rb
class Superuser < ActiveRecord::Base
  after_create :scrape_insta

  def scrape_insta
    @profile = InstaScrape.user_info(self.insta_username)
    @posts = InstaScrape.user_posts(self.insta_username)
    self.following_count = @profile.following_count.scan(/\d*/).join.to_i
    self.number_of_posts = @profile.post_count.scan(/\d*/).join.to_i
    self.image = @profile.image
    self.engagement_rate = engagement_rate
    self.description = @profile.description
    self.followers_count = followers_count
    self.super_score = super_score
    # self.save
  end

  def followers_count
    count = @profile.follower_count
    # instagram will return 10k for 10000 followers.
    if count.include? 'k'
      count = count.gsub('k', '00')
    end
    count = count.scan(/\d*/).join.to_i
    count
  end


  def engagement_rate
    total_like = 0
    if (@posts == nil)
      engagement_rate = 0
    else
      @posts.each do |post|
        total_like += post.likes
      end
      engagement_rate = ((total_like / 10.0) / followers_count) * 100
      engagement_rate.round(2)
    end
  end

  def super_score
      # getting points for number of followers
      score = case self.followers_count
      when 0..500 then 2
      when 500..800 then 3.5
      when 800..1000 then 7
      when 1000..3000 then 10.5
      when 3000..7000 then 14
      when 7000..10000 then 17.5
      when 10000..30000 then 21
      when 30000..60000 then 24.5
      when 90000..150000 then 28
      when 150000..200000 then 31.5
      when 200000..9000000000 then 35
      end
      # getting points for number of following
      if self.following_count >= 200
        score += 2
      end
      if self.following_count < 1000
        score +=2
      end
      if self.following_count < self.followers_count
        score += 6
      end
      # getting points for number of posts
      score += case self.number_of_posts
      when 0..10 then 2
      when 10..100 then 4
      when 300..600 then 6
      when 600..1000 then 8
      when 1000..50000 then 10
      end
      # getting points for description length
      score += case self.description.length
      when 0..10 then 2.5
      when 10..30 then 5
      when 30..80 then 7.5
      when 80..300 then 10
      end
      # Getting points for engagement rate
      if self.followers_count < 500
        score += case self.engagement_rate.round
        when 0..5 then 7
        when 5..25 then 14
        when 25..40 then 21
        when 40..60 then 28
        when 80..1000 then 35
        end
      elsif self.followers_count >= 500 && self.followers_count <= 5000
        score += case self.engagement_rate.round
        when 2..4 then 7
        when 4..7 then 14
        when 7..10 then 21
        when 10..15 then 28
        when 15..1000 then 35
        end
      else #self.followers_count >= 5000
        score += case self.engagement_rate.round
        when 0..1 then 3
        when 1..2 then 7
        when 2..4 then 14
        when 4..7 then 21
        when 7..10 then 28
        when 10..1000 then 35
        end
      end
      score
    end
  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
# require 'open-uri'
class PagesController < ApplicationController

  def home
    @superuser = Superuser.new
  end

  def stat
    if params[:superuser][:insta_username].nil? || params[:superuser][:insta_username].empty? ||
      params[:superuser][:insta_usercomp].nil? || params[:superuser][:insta_usercomp].empty?
      redirect_to root_path
      flash[:notice] = "Username cannot be empty"
    elsif params[:superuser][:insta_username] == params[:superuser][:insta_usercomp]
      redirect_to root_path
      flash[:notice] = "Try to compete with someone else than yourself ;)"
    else
      begin

        create
      rescue Capybara::ElementNotFound
        redirect_to root_path
        flash[:notice] = "Username not found, please check that it exists "
      end
      if @superuser.engagement_rate == 0
        flash[notice] = "You didn't get point for engagement rate because your account is set as private"
      end
      if @usercmp.engagement_rate == 0
        flash[notice] = "Your opponents didn't get point for engagement rate because his account is set as private"
      end
    end
  end

  def create
    @superuser = Superuser.new
    @superuser = Superuser.create(superuser_params)

    # Changing params to make stats for the opponents
    tmp = params[:superuser][:insta_username]
    params[:superuser][:insta_username] = params[:superuser][:insta_usercomp]
    params[:superuser][:insta_usercomp] = tmp
    @usercmp = Superuser.new
    @usercmp = Superuser.create(superuser_params)
  end

  def superuser_params
    params.require(:superuser).permit(:insta_username, :insta_usercomp)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>Super Battle</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>
  <body>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/pages/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible slideDown" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/pages/home.html.erb
  <div class="text-center"> <%= render 'flashes' %></div>
  <br>
  <div class="text-center">
    <h2>Super Battle</h2>
  </div>
  <br>
  <h1 class="text-center">Choose which instagram <br> accounts you want to compare</h1>
  <br>

  <div class="text-center">
    <%= simple_form_for(@superuser, html: {class: "form-inline"}, url: stat_path) do |f| %>
    <%= f.error_notification %>
    <span id="no1">1 </span>
    <%= f.input :insta_username, label: false,required: false, placeholder: 'You',input_html: {class: "red", id: "red_input"} %>
    <span id="no2">2 </span>
    <%= f.input :insta_usercomp, label: false,required: false, placeholder: 'Him/her', input_html: {class: "form-control blue", id:"blue_input"} %>
    <br>
    <br>
    <%= f.button :submit , class: 'btn btn-primary', value: "Fight" %>
    <% end %>
    <%= image_tag "SUPER_BATTLE_01.gif", id: "fighter" %>
<div class="container">

  </div>
</div>

app/views/pages/stat.html.erb
<div class="stat-container">
  <div class="text-center">
    <%= render 'flashes' %>
  </div>

  <div class="text-center">
    <h1>Super battle</h1>
  </div>

  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-md-6">
        <div class="info-container text-center">
          <h1 id="username">
            <%= @superuser.insta_username %></h1>
            <% if (@superuser.super_score > @usercmp.super_score) %>
            <h2 class="text-red winner">
              Wins </h2>
              <% else %>
              <h2 class="text-blue winner">
                Loses </h2>
                <% end %>
                <%= image_tag 'mask.png', class: "mask shadowed"  %>
                <h2 class="mask_name">The furious Giant</h2>
                <h3 class="mask_p"> Lorem ipsum dolor sit amet, consectetur adipisicing elit. Reiciendis, voluptates.</h3>
                <br>
                <h4 class="stats"> <%= @superuser.followers_count %> Followers </h4>
                <p class="stat_p">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cumque, explicabo.</p>
                <h4 class="stats"><%= @superuser.engagement_rate %>% commitement rate</h4>
                <p class="stat_p">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Repudiandae, quibusdam.</p>
                <h4 class="stats"><%= @superuser.number_of_posts %> Number of posts</h4>
                <p class="stat_p">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Velit, eligendi.</p>
              </div>
            </div>


            <div class="col-xs-12 col-md-6">
              <div class="info-container text-center">
                <h1 id="username">
                  <%= @usercmp.insta_username %> </h1>
                  <% if @superuser.super_score < @usercmp.super_score %>
                  <h2 class="text-red winner">
                    Wins </h2>
                    <% else %>
                    <h2 class="text-blue winner">
                      Loses </h2>
                      <% end %>

                      <%= image_tag 'mask2.png', class: "mask" %>
                      <div class="vertical_line">
                      </div>
                      <h2 class="mask_name">
                        El Moucho
                      </h2>
                      <h3 class="mask_p"> Lorem ipsum dolor sit amet, consectetur adipisicing elit. Reiciendis, voluptates.</h3>
                      <br>
                      <h4 class="stats"> <%= @usercmp.followers_count %> Followers</h4>
                      <p class="stat_p">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cumque, explicabo.</p>
                      <h4 class="stats"> <%= @usercmp.engagement_rate %>% commitment rate</h4>
                      <p class="stat_p">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Repudiandae, quibusdam.</p>
                      <h4 class="stats"> <%= @usercmp.number_of_posts %> Number of posts</h4>
                      <p class="stat_p">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Velit, eligendi.</p>
                    </div>
                  </div>
                  <br>
                </div>
              </div>
            </div>
            <div class="share text-center">
              <button class="restart"> <%= link_to "Restart", root_path %></button>
              <h1 class="yellow">Partage sur les réseaux sociaux !</h1>
              <ul class="list-inline">
                <li class="btn-share">
                  <i class="fa fa-facebook fa-2x" aria-hidden="true"></i>
                </li>
                <li class="btn-share">
                  <i class="fa fa-instagram fa-2x" aria-hidden="true"></i>
                </li>
                <li class="btn-share">
                  <i class="fa fa-twitter fa-2x" aria-hidden="true"></i>
                </li>
              </ul>
              <h1 class="yellow">Get More !</h1>
              <p class="stat_p">
                Ne naisse pas la garde !
                Laisse ton mail et découvre contre qui <br>
                et combien de fois tu as été affronté à ton insu !
              </p>
              <p class="stat_p">
                Je veux recevoir ces infos:
                <ul class="list-inline">
                  <li class="btn-share" id="btn-days"><p class="btn_text"> à chaque fois </p></li>
                  <li class="btn-share" id="btn-days"><p class="btn_text"> chaque jour </p></li>
                  <li class="btn-share" id="btn-days"><p class="btn_text"> chaque mois </p></li>
                  <li class="btn-share" id="btn-days"><p class="btn_text"> chaque semaine </p></li>
                </ul>
              </p>
              <%= simple_form_for(@superuser, html: {class: "form-inline"}, url: stat_path) do |f| %>
              <%= f.error_notification %>
              <%= f.input :insta_username, label: false,required: false, placeholder: 'entre ton adresse mail! ',input_html: {class: "email_form", id: "email_input"} %>
              <%= f.button :submit , class: 'btn-share btn-ok', value: "OK" %>
              <% end %>
              <br>
              <h1 class="logo">Super Battle</h1>
              <br>
              <br>
              <p class="credits"> Idée originale: Dire Agency / DA: CLub Néon x Pablo Grand Mourcel / Illustrations : Pablo Grand Mourcel </p>
            </div>